server:
  port: 1112

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: false