server:
  port: 1111

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/
    register-with-eureka: true
    fetch-registry: true
  server:
    enable-self-preservation: false